### ISSUE TITLE
Cannot set maximum DPI (16000) 

### ISSUE THREAD

**Issue by DBarthe** [mbuesch/razer#109]
Hello, 

I have a mouse (mamba TE) which can go to 16000dpi, but maximum I can set is 10000dpi from qrazerd.

Don't know where this restriction comes from. Do you have any information on this ?

Otherwise thanks for this project :+1:

**Comment by DBarthe** [comment]
This small fix worked for me... can it be merged ?

**Comment by mbuesch** [comment]
Thanks a lot for your contribution.
Looking forward to the next one :)
