### ISSUE TITLE
razerd: error while loading shared libraries: librazer.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by stormsz** [mbuesch/razer#116]
https://imgur.com/a/WtHmse0

can you help me? i already reinstalled everything and as you can see from the print i DO have the files...
sorry i'm new to linux, using manjaroOS with kde plasma, my mouse is razer naga. and aside from that error, the software wont find my mouse either.

**Comment by stormsz** [comment]
Hello, no, i formated my machine and everything is working now.


2018-06-10 16:23 GMT+01:00 Michael Büsch <notifications@github.com>:

**Comment by mbuesch** [comment]
Thanks.
I'll close this issue.
