### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by 360CodeSafe** [mbuesch/razer#122]
librazer/cypress_bootloader.c  in line 255. 

int cypress_open(struct cypress *c, struct libusb_device *dev,
		 void (*assign_key)(uint8_t *key))
{
	int err;

	BUILD_BUG_ON(sizeof(struct cypress_command) != 64);
	BUILD_BUG_ON(sizeof(struct cypress_status) != 64);

return -1; //FIXME: Does not work, yet.
//Dead code
	memset(c, 0, sizeof(*c));
	if (!assign_key)
		assign_key = cypress_assign_default_key;
	c->assign_key = assign_key;

	c->usb.dev = dev;
	c->usb.bConfigurationValue = 1;
	err = razer_usb_add_used_interface(&c->usb, 0, 0);
	if (err)
		return err;
	err = razer_generic_usb_claim(&c->usb);
	if (err) {
		razer_error("cypress: Failed to open and claim device\n");
		return err;
	}

	/* EP numbers are hardcoded */
	c->ep_in = 0x81;
	c->ep_out = 0x02;

	return 0;
}

**Comment by mbuesch** [comment]
Yes, sure. Please read the FIXME comment.
