### ISSUE TITLE
Awake from sleep when mouse is moving

### ISSUE THREAD

**Issue by jichen-yang** [mbuesch/razer#133]
My operation system is Ubuntu 20.04 in Thinkpad L440 with DeathAdder 2013. When I move the mouse, the laptop can wake up from the sleep, whereas it does not happen for other mouses.

**Comment by mbuesch** [comment]
Hi.
Thanks for your comment.
Unfortunately I don't think this has anything to do with this razercfg tool.
Please check the power management options in your operating system and your UEFI/BIOS.
You can probably disable the wakeup-by-usb somewhere along these settings.

**Comment by mbuesch** [comment]
Did you find a solution to the problem?

**Comment by jichen-yang** [comment]
> Did you find a solution to the problem?

I found a solution to the wakeup issue, [https://askubuntu.com/questions/509017/desktop-wakes-from-suspend-at-random-14-04](url)
