### ISSUE TITLE
Naga Hex not detected (model# RZ01-0075)?

### ISSUE THREAD

**Issue by conihorse** [mbuesch/razer#25]
Hi
I've just installed via the Arch AUR, but not having much luck after that. Any suggestions?
Thanks.

 coni@Burt  ~  uname -a
Linux Burt 3.16.1-1-ARCH #1 SMP PREEMPT Thu Aug 14 07:40:19 CEST 2014 x86_64 GNU/Linux
 coni@Burt  ~  lsusb
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 009 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 002: ID 046d:c517 Logitech, Inc. LX710 Cordless Desktop Laser
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 007: ID 058f:3880 Alcor Micro Corp. 
Bus 001 Device 006: ID 1852:50d0 GYROCOM C&C Co., LTD 
Bus 001 Device 004: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 008: ID 0b0e:0410 GN Netcom 
Bus 001 Device 005: ID 046d:c043 Logitech, Inc. MX320/MX400 Laser Mouse
Bus 001 Device 002: ID 05e3:0607 Genesys Logic, Inc. Logitech G110 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 002: ID 1532:0041 Razer USA, Ltd 
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
 coni@Burt  ~  razercfg -v
Razer device configuration tool
Version 0.29
 coni@Burt  ~  razercfg -s
 coni@Burt  ~ 

**Comment by Zeioth** [comment]
My Razer naga it's working fine in xubuntu 14.04.
Driver version 0.30.

**Comment by mbuesch** [comment]
Can somebody try with a recent razercfg (0.31)?
There were some improvements to the naga driver.
The USB device ID for 0041 still has to be added manually in librazer.c:
`USB_MOUSE(0x1532, 0x0041, &razer_naga_base_ops),`

**Comment by mbuesch** [comment]
The USB-ID 0x0041 was added to razercfg-0.33.
So the device should be supported.

**Comment by Zeioth** [comment]
Good to see you kicking and alive. Thank you for your great job mbuesch!
