### ISSUE TITLE
razercfg vs qrazercfg

### ISSUE THREAD

**Issue by ptrj** [mbuesch/razer#39]
whit qrazercfg i can set every resolution, like in Res5 2500DPI:

![screen1](https://cloud.githubusercontent.com/assets/5557356/5783703/cc220428-9dc5-11e4-97d6-555b2a7c90c7.png)

but when i try razercfg: 
ptrj@kuralin:~$ razercfg -r 5:2500
Invalid resolution 2500
ptrj@kuralin:~$ razercfg -r 5:1000
ptrj@kuralin:~$ razercfg -r 5:1800
ptrj@kuralin:~$ razercfg -r 5:2500
Invalid resolution 2500

it doesnt work :-(

=========
prtj@kuralin:~$ razercfg -v
Razer device configuration tool
Version 0.31

**Comment by mbuesch** [comment]
Please try something like this:

$ razercfg -r 5:1000x1000
or
$ razercfg -r 5:3

This should both work and result in 1000 DPI x 1000 DPI

**Comment by ptrj** [comment]
ptrj@kuralin:~$ razercfg -r 5:1000x1000
Invalid resolution 1000
ptrj@kuralin:~$ razercfg -r 5:3
ptrj@kuralin:~$ razercfg -R
Profile  1*:    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile  2 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile  3 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile  4 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile  5 :    1 (800/800 DPI),  2 (1800/1800 DPI), *3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile  6 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile  7 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile  8 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile  9 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 10 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 11 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 12 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 13 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 14 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 15 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 16 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 17 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 18 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 19 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)
Profile 20 :    1 (800/800 DPI), *2 (1800/1800 DPI),  3 (3500/3500 DPI),  4 (5600/5600 DPI),  5 (10000/10000 DPI)

nothing, profil 5 is on 10000DPI

**Comment by ptrj** [comment]
btw: led colors works perfect :-)

**Comment by mbuesch** [comment]
1000x1000 is not a valid request for your configuration.
And the -r 5:3 request seems to have worked just fine. Profile 5 is set to resolution index 3 (which is 3500x3500).

**Comment by ptrj** [comment]
is it posibble to set this five resolution colomn permanently ?

**Comment by mbuesch** [comment]
I think for this device there currently is no way to do so.

**Comment by ptrj** [comment]
i allready understand how parameter "-r" das work :-) i miss parameter for set this five "resolution DPI" column wich ar in qrazercfg and i can change it. Problem is when i reset my PC, mouse is reseted to default. And i muss open qrazercfg and setup mouse again :-(

**Comment by mbuesch** [comment]
Yes, I understand.
There currently is no way to do that.

I will take patches or pulls adding such a command to razercfg.

**Comment by ptrj** [comment]
much thanks
