### ISSUE TITLE
[Taipan] Failed to read firmware version

### ISSUE THREAD

**Issue by Fragan** [mbuesch/razer#4]
Hello,

Thanks to you to provide Razer mice support for Linux.

Today, I have installed the latest version of razercfg on Ubuntu 13.10 (3.11.0-12-generic x86_64) for my Razer Taipan.

The installation went smoothly, but when I start `razerd` I have the following error message:

```
$ sudo razerd
Razer device service daemon
librazer: No config file /etc/razer.conf present. Ignoring.
librazer: razer-taipan: Failed to read firmware version

```

I would be happy to provide you any helping information.

Regards,
Fragan.

**Comment by Niler851** [comment]
So i did my installation with yaourt can i still apply this fix ? cant open the program and have a similar issue as descibed above.
