### ISSUE TITLE
Systemctl fails to start razerd on fresh install

### ISSUE THREAD

**Issue by jacobmischka** [mbuesch/razer#42]
I just made a fresh install of arch earlier this week, and no attempts to install and run razercfg have been successful. It's possible this is my fault, though I'm not sure since I believe I've followed the instructions.

Installing is successful, though upon trying to start razerd I receive the following: http://vpaste.net/DZgMc

**Comment by mbuesch** [comment]
Does it work, if you try to run razerd manually?

**Comment by jacobmischka** [comment]
No it does not, http://vpaste.net/0LsbR

**Comment by mbuesch** [comment]
You need to configure your ld environment to include /usr/local/lib
See /etc/ld.so.conf and man ldconfig.
