### ISSUE TITLE
Saving the settings

### ISSUE THREAD

**Issue by samthewildone** [mbuesch/razer#51]
Hi guys !

This isn't much of a serious issue but for me it is. 
I'm using Ubuntu Gnome 15.10 64bit and the program
works but, every time I reboot the machine I have to set to 
the settings I like. 

Is there a way I can set my current settings to default 
so when I reboot/reset they stick ?

Thanks in advance.

**Comment by mbuesch** [comment]
This is a duplicate of https://github.com/mbuesch/razer/issues/49
