### ISSUE TITLE
uninstall.sh should also remove egg-info

### ISSUE THREAD

**Issue by z3ntu** [mbuesch/razer#55]
`rm /usr/lib/python3.5/site-packages/razercfg-*.egg-info` should do it

**Comment by mbuesch** [comment]
Yes. Nice catch. I think it should also be done for the dist-packages directory. uninstall.sh already does this for pyrazer module.
Could you send a pull request, please?

**Comment by z3ntu** [comment]
Will do earliest tomorrow

**Comment by z3ntu** [comment]
Like this? #57

**Comment by mbuesch** [comment]
Thanks.
