### ISSUE TITLE
README to markdown + add device support

### ISSUE THREAD

**Issue by janstuemmel** [mbuesch/razer#61]
Hi,
would be nice if the readme was updated to markdown and includes the supported device table.
i can make a suggestion.
PS: nice work!

**Comment by z3ntu** [comment]
Feel free to send pull requests. The supported devices would be nice indeed in the readme of this repository.

**Comment by mbuesch** [comment]
>Feel free to send pull requests.

Yes, please send a pull request.

>The supported devices would be nice indeed in the readme of this repository.

Meh. That effectively means maintaining it in two places. Rather just add a link to the list.
