### ISSUE TITLE
qrazercfg-applet doesn't get installed by CMake

### ISSUE THREAD

**Issue by z3ntu** [mbuesch/razer#70]

**Comment by mbuesch** [comment]
This currently is expected, because icons are not installed, too. And the applet depends on the icons.
Feel free to submit pull requests to get both installed and working together.

**Comment by mbuesch** [comment]
And these two changes are the last required ones for the next release. So 0.34 will be released after those.

**Comment by mbuesch** [comment]
I added the applet to cmake-install without icons in 0.34. So it will show up without an icon for now. But it still is usable that way.
