### ISSUE TITLE
lachesis set led mode and color issue

### ISSUE THREAD

**Issue by LawrenceBobrov** [mbuesch/razer#74]
Hi,guys! Thank you very much for this cool driver pack!
Actually, everything works almost fine with my lachesis (firmware v. 1.94) in Ubuntu 14.04 x64.
I can switch on and off both ScrollWheel and GrowlingLogo. But I can not change led mode and color.
I tryed to do it (1)on the fly, (2) turning off LED, setting up color, and turning led LED on, (3)restarting services,etc.
It seems like a bug, but I do not have enough knowledge to debug this driver issue myself. Could you,please,help?

**Comment by mbuesch** [comment]
>But I can not change led mode and color.

Is that a Lachesis 5600 DPI?
If so, what does "cannot change" mean?

**Comment by LawrenceBobrov** [comment]
Hello,@mbuesch! Thank you for your reply!

> Is that a Lachesis 5600 DPI?

No. It is not. 

> what does "cannot change" mean?

I try to modify color and led modes with the following commands: 
`razercfg -c Scrollwheel:FF0000`
`razercfg -c GlowingLogo:ffff00`
`razercfg -m Scrollwheel:breathing`
`razercfg -m GlowingLogo:spectrum`
But they do not affect mouse at all. As I mentioned above I also tried to turn led off before changing color, restarting razerd service, etc.

But the commands for turning leds on and off work fine:
`razercfg -l Scrollwheel:off`
`razercfg -l Scrollwheel:on`
`razercfg -l GlowingLogo:off`
`razercfg -l GlowingLogo:on`

**Comment by z3ntu** [comment]
@LawrenceBobrov Which "Lachesis" is it (as it is not the 5600DPI variant)?

**Comment by LawrenceBobrov** [comment]
@z3ntu 
This is Lachesis with 4000dpi which is called "Lachesis Classic" in razercfg.
http://www.razersupport.com/gaming-mice/razer-lachesis/

**Comment by mbuesch** [comment]
>This is Lachesis with 4000dpi which is called "Lachesis Classic" in razercfg.

Are you sure this one has hardware support for color leds?
My Lachesis classic does not have that.

Can you please tell us the USB IDs and the firmware version of your device?

**Comment by LawrenceBobrov** [comment]
@mbuesch 
Actually, I'm not sure about it. I recently got this mouse from my friend (he did not use it for a long time) but he said it could probably change color.
```
razercfg -V
Mouse:Lachesis Classic:USB-001-002:1532-000C-0: Firmware version 1.94
```

It looks like lsusb information is included, but I'm not 100% sure. So:
```
lsusb |grep Razer
Bus 001 Device 002: ID 1532:000c Razer USA, Ltd
```

**Comment by mbuesch** [comment]
It's pretty certain that this device does not have color LEDs.
So everything is fine.
I'm closing the issue. If there still is some problem, please re-open.

**Comment by LawrenceBobrov** [comment]
@mbuesch 
Thank you very much and sorry for this situation with colors.
However, there is still an issue with LED modes as I mentioned above.
Should this mouse support them?

**Comment by mbuesch** [comment]
>Should this mouse support them?

Sorry for the confusion.
The Lachesis classic doesn't support LED mode changes either.

**Comment by LawrenceBobrov** [comment]
@mbuesch 
Thank you for the clarification!
