### ISSUE TITLE
Diamondback 2015 support?

### ISSUE THREAD

**Issue by lumirsliva** [mbuesch/razer#88]
Hi, anyone tried Diamondback 2015 support? Does it work, and if not, can you work on it please?

**Comment by mbuesch** [comment]
You can see a list of supported devices together with their USB IDs here:
https://bues.ch/h/razercfg#device_support

Anything not listed there will not work.

**Comment by lumirsliva** [comment]
Does this help for a starter? Let me know, if you'd need any of my help, I am not a developer tho.

Bus 002 Device 006: ID 1532:004c Razer USA, Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x004c 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

**Comment by mbuesch** [comment]
Somebody who owns that device and is able to reverse engineer the USB wire protocol is needed.

**Comment by trainman419** [comment]
I recently picked up a Diamondback Collector's Edition. I haven't tried it with Windows yet, but I did try the Synapse 2.0 driver (a copy of the imperator driver), and that did not work.

I'll try to capture a packet dump the next time I'm on Windows, but this is my work computer and I don't use Windows very often, so it may be a while.

**Comment by mbuesch** [comment]
Here is an initial implementation of a Diamondback 2015 driver:
https://github.com/mbuesch/razer/pull/98

Can you please try it and give us some feedback?

**Comment by mbuesch** [comment]
Bump. Can somebody please test this https://github.com/mbuesch/razer/pull/98
Thanks a lot!

**Comment by mbuesch** [comment]
Is there anybody who can test this? https://github.com/mbuesch/razer/pull/98

**Comment by mbuesch** [comment]
I merged support for this into razercfg 0.39.
If there are any problems with it, please re-open this issue.
