### ISSUE TITLE
How Do I open this?

### ISSUE THREAD

**Issue by INeedHelpNoob** [mbuesch/razer#93]
I'm using ubuntu 16.04 and I can't seem to open it. I have installed and done all the instructions with no errors just dont know how to open it. Sorry for being a noob

**Comment by mbuesch** [comment]
There basically are three applications:

qrazercfg - The graphical user interface
qrazercfg-applet - The graphical tray applet
razercfg - The command line interface

Just run these just like any other application on your operating system.

**Comment by INeedHelpNoob** [comment]
Is there any commands I can do to set the dpi?

**Comment by INeedHelpNoob** [comment]
I fixed the issue and discovered why it wasn't working but thanks for the help and cheers for the program

**Comment by mbuesch** [comment]
if you run qrazercfg a graphical dialog box will open.
It will look similar to this https://bues.ch/images/qrazercfg.png
The exact layout depends on your hardware.

**Comment by mbuesch** [comment]
>I fixed the issue and discovered why it wasn't working but thanks for the help and cheers for the program

Have fun! :)
