### ISSUE TITLE
Unable to start applet?

### ISSUE THREAD

**Issue by tominglis** [mbuesch/razer#96]
I have the qrazercfg-applet installed on Ubuntu 16.04.

Unfortunately the applet does not seem to load and I can't see any option in qrazercfg to enable it?

I followed the instructions on here to install the application:

http://www.webupd8.org/2016/06/configure-razer-mice-in-linux-with.html

**Comment by polyzen** [comment]
https://github.com/mbuesch/razer/blob/master/README.md

**Comment by mbuesch** [comment]
The applet will not start automatically, unless you put it into your autostart.

**Comment by mbuesch** [comment]
Closing the issue.
If you have further questions, please re-open it.
Thanks for your question.
